---
- name: install httpd package using playbook
  hosts: all
  become: true
  tasks:
    - name: install git package
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    - name: install httpd package
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
      notify: restart the service

    - name: start the httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: install apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      notify: restart the apache2

    - name: start the apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: copy the index file
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
  handlers:
    - name: restart the service
      service:
        name: httpd
        state: restarted

    - name: restart the apache2
      service:
        name: apache2
        state: restarted
